url: 'https://mysite.com/'

# Enable CloudCannon UI
cloudcannon:
  data: true

# Sass partials directory
sass:
  sass_dir: _sass
  style: compressed

# Global permalinks
permalink: /:categories/:year/:title

# Collections configurations
collections:
  pages:
    output: true
    permalink: /:title

# Defaults
defaults:
  -
    scope:
      path: "/posts" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: blog
      title:
      subtitle:
      author:
      description: SEO content. Limit to 160 characters.
      preview_image:
      preview_image_alt_text:
      categories: []
      tags: []
      keywords: []
      sections:

# Plugins installed
plugins:
  - jekyll-sitemap
  - jekyll-responsive-image
  - jekyll-webp

# Configuration of the jekyll-responsive-image plugin
responsive_image:
  template: _includes/templates/image-tag-lazy.html
  sizes:
    - width: 360
    - width: 480
    - width: 600
    - width: 800
    - width: 1400
  base_path: assets/images
  output_path_format: assets/images/srcset/%{width}/%{basename}

# Configuration for the WebP Generator Plugin
webp:
  enabled: true
  quality: 75
  img_dir: ["/assets/images/"]
  nested: true

# Configuration of the compress_html layout
compress_html:
  comments: all # Removes all comments; remove this line to enable comments in production site
